import type { Campaign, GraphEdge, LatticeNode, LeaderCategory, MeshOrgan, ThreatArc } from "./types";
import { FIELD_LEADERS } from "./radar";

export const LEADERS: LeaderCategory[] = FIELD_LEADERS;

export const ESTATE_NODES: LatticeNode[] = [
  {
    id: "estate-immune",
    kind: "estate",
    name: "IMMUNE Space",
    lat: 40.71,
    lon: -74.01,
    status: "nominal",
    provenance: "REFERENCE",
    summary: "Hugging Face Space SZLHOLDINGS/immune — verifiable AI defense matrix.",
    tags: ["hf", "space", "yawar"],
  },
  {
    id: "estate-a11oy",
    kind: "estate",
    name: "a11oy Command",
    lat: 51.51,
    lon: -0.13,
    status: "nominal",
    provenance: "REFERENCE",
    summary: "Governed inference console. Receipts in ≡ receipts out.",
    tags: ["a11oy", "command"],
  },
  {
    id: "estate-khipu",
    kind: "estate",
    name: "Khipu-1.5B",
    lat: 37.39,
    lon: -122.08,
    status: "watch",
    provenance: "REFERENCE",
    summary: "Sovereign 1.5B governed agent. High-value model-theft target.",
    tags: ["model", "khipu"],
  },
  {
    id: "estate-killinchu",
    kind: "estate",
    name: "killinchu C-UAS",
    lat: 32.9,
    lon: -117.16,
    status: "nominal",
    provenance: "REFERENCE",
    summary: "Counter-UAS mesh. Lattice-style effector for the physical domain.",
    tags: ["cuas", "mesh"],
  },
  {
    id: "estate-github",
    kind: "estate",
    name: "szl-holdings",
    lat: 47.61,
    lon: -122.33,
    status: "nominal",
    provenance: "REFERENCE",
    summary: "GitHub org — source of truth for IMMUNE, a11oy, killinchu.",
    tags: ["github", "source"],
  },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: "cmp-prompt-swarm",
    name: "Prompt-injection swarm",
    actor: "APT-GHOST (RANGE)",
    target: "estate-immune",
    technique: "LLM prompt injection against SENTRA",
    atlas: "AML.T0051",
    owasp: "LLM01",
    severity: "high",
    provenance: "RANGE",
    summary:
      "Simulated adversary flooding IMMUNE with unsigned intents and jailbreak wrappers. White-hat RANGE only.",
    status: "inbound",
    rangeOnly: true,
  },
  {
    id: "cmp-khipu-exfil",
    name: "Khipu weight exfil",
    actor: "APT-MIRROR (RANGE)",
    target: "estate-khipu",
    technique: "Exfiltration via inference API",
    atlas: "AML.T0024",
    owasp: "LLM02",
    severity: "critical",
    provenance: "RANGE",
    summary: "Simulated model-theft against SZL-Khipu-1.5B. STRIKE authorized only on the RANGE node.",
    status: "inbound",
    rangeOnly: true,
  },
  {
    id: "cmp-supply-poison",
    name: "Kernel supply poison",
    actor: "APT-TWINE (RANGE)",
    target: "estate-github",
    technique: "ML supply-chain compromise",
    atlas: "AML.T0010",
    owasp: "LLM03",
    severity: "critical",
    provenance: "RANGE",
    summary: "Simulated tamper of szl-governed-norm / szl-kernels receipts. YAWAR must catch divergence.",
    status: "inbound",
    rangeOnly: true,
  },
  {
    id: "cmp-ledger-tamper",
    name: "YAWAR rewrite attempt",
    actor: "APT-FORGE (RANGE)",
    target: "estate-immune",
    technique: "Receipt-chain rewrite",
    atlas: "AML.T0031",
    owasp: "LLM03",
    severity: "critical",
    provenance: "RANGE",
    summary: "Adversary tries to mutate a sealed receipt. Recompute must fail closed.",
    status: "inbound",
    rangeOnly: true,
  },
  {
    id: "cmp-kev-linux",
    name: "KEV watch · Linux IPv6 priv-esc",
    actor: "in-the-wild (CISA)",
    target: "estate-a11oy",
    technique: "CVE-2026-53362 privilege escalation",
    atlas: "T1068",
    owasp: "LLM03",
    severity: "high",
    provenance: "LIVE",
    summary: "CISA KEV added 2026-08-27. Defensive PATCH/ISOLATE authorized. No live exploitation.",
    status: "watching",
    rangeOnly: false,
  },
  {
    id: "cmp-kev-citrix",
    name: "KEV watch · Citrix NetScaler",
    actor: "in-the-wild (CISA)",
    target: "estate-killinchu",
    technique: "CVE-2026-8452 memory bounds",
    atlas: "T1190",
    owasp: "LLM03",
    severity: "high",
    provenance: "LIVE",
    summary: "Edge appliance class. Isolate / patch playbook only.",
    status: "watching",
    rangeOnly: false,
  },
  {
    id: "cmp-react-rsc",
    name: "KEV watch · React RSC RCE",
    actor: "in-the-wild (CISA)",
    target: "estate-immune",
    technique: "CVE-2025-55182 React Server Components",
    atlas: "T1190",
    owasp: "LLM03",
    severity: "critical",
    provenance: "LIVE",
    summary: "Known exploited RSC RCE. Hunt + patch the estate surface. STRIKE blocked.",
    status: "watching",
    rangeOnly: false,
  },
];

export const SEED_ARCS: ThreatArc[] = [
  { id: "arc-1", from: "cmp-prompt-swarm", to: "estate-immune", intensity: 0.86, technique: "AML.T0051", active: true },
  { id: "arc-2", from: "cmp-khipu-exfil", to: "estate-khipu", intensity: 0.72, technique: "AML.T0024", active: true },
  { id: "arc-3", from: "cmp-supply-poison", to: "estate-github", intensity: 0.64, technique: "AML.T0010", active: true },
  { id: "arc-4", from: "cmp-ledger-tamper", to: "estate-immune", intensity: 0.55, technique: "AML.T0031", active: true },
  { id: "arc-5", from: "cmp-kev-linux", to: "estate-a11oy", intensity: 0.4, technique: "T1068", active: true },
  { id: "arc-6", from: "cmp-kev-citrix", to: "estate-killinchu", intensity: 0.38, technique: "T1190", active: true },
  { id: "arc-7", from: "cmp-react-rsc", to: "estate-immune", intensity: 0.7, technique: "T1190", active: true },
];

export const THREAT_ORIGINS: LatticeNode[] = [
  {
    id: "cmp-prompt-swarm",
    kind: "range",
    name: "APT-GHOST",
    lat: 55.75,
    lon: 37.62,
    status: "hostile",
    provenance: "RANGE",
    summary: "RANGE persona. Prompt-injection swarm.",
    tags: ["range", "llm"],
  },
  {
    id: "cmp-khipu-exfil",
    kind: "range",
    name: "APT-MIRROR",
    lat: 31.23,
    lon: 121.47,
    status: "hostile",
    provenance: "RANGE",
    summary: "RANGE persona. Model theft.",
    tags: ["range", "exfil"],
  },
  {
    id: "cmp-supply-poison",
    kind: "range",
    name: "APT-TWINE",
    lat: 1.35,
    lon: 103.82,
    status: "hostile",
    provenance: "RANGE",
    summary: "RANGE persona. Supply-chain poison.",
    tags: ["range", "supply"],
  },
  {
    id: "cmp-ledger-tamper",
    kind: "range",
    name: "APT-FORGE",
    lat: -23.55,
    lon: -46.63,
    status: "hostile",
    provenance: "RANGE",
    summary: "RANGE persona. Ledger rewrite.",
    tags: ["range", "integrity"],
  },
  {
    id: "cmp-kev-linux",
    kind: "threat",
    name: "KEV Linux",
    lat: 50.11,
    lon: 8.68,
    status: "watch",
    provenance: "LIVE",
    summary: "CISA KEV watch node.",
    tags: ["kev", "linux"],
  },
  {
    id: "cmp-kev-citrix",
    kind: "threat",
    name: "KEV Citrix",
    lat: 25.76,
    lon: -80.19,
    status: "watch",
    provenance: "LIVE",
    summary: "CISA KEV watch node.",
    tags: ["kev", "edge"],
  },
  {
    id: "cmp-react-rsc",
    kind: "threat",
    name: "KEV RSC",
    lat: 37.48,
    lon: -122.15,
    status: "watch",
    provenance: "LIVE",
    summary: "React Server Components RCE watch.",
    tags: ["kev", "rsc"],
  },
];

export const OP_COPY: Record<
  string,
  { title: string; blurb: string; modeled: boolean }
> = {
  ISOLATE: {
    title: "Isolate",
    blurb: "Quarantine the estate node. Cut east-west. Palantir object lock.",
    modeled: false,
  },
  TARPIT: {
    title: "Tarpit",
    blurb: "Slow the inbound campaign. Absorb without executing.",
    modeled: true,
  },
  SINKHOLE: {
    title: "Sinkhole",
    blurb: "Redirect simulated C2 into a dark well. RANGE only.",
    modeled: true,
  },
  HUNT: {
    title: "Hunt",
    blurb: "Search IOCs across estate objects. CIA-style collection plan.",
    modeled: false,
  },
  ATTRIBUTE: {
    title: "Attribute",
    blurb: "Build motive / capability / opportunity dossier. MODELED until LIVE evidence.",
    modeled: true,
  },
  PATCH: {
    title: "Patch",
    blurb: "Apply the defensive control. KEV-driven hardening.",
    modeled: false,
  },
  DECEIVE: {
    title: "Deceive",
    blurb: "Stand up a honeypot twin. Deny useful feedback to the actor.",
    modeled: true,
  },
  INTERDICT: {
    title: "Interdict",
    blurb: "Cut the arc. Lattice effector: click → machine tasking on RANGE mesh.",
    modeled: true,
  },
  STRIKE: {
    title: "Strike (RANGE)",
    blurb: "Collapse simulated attacker infrastructure. Never emitted at the public internet.",
    modeled: true,
  },
};

export const MESH_ORGANS: MeshOrgan[] = [
  {
    id: "immune",
    name: "IMMUNE",
    role: "admission + receipts",
    domain: "governed AI defense",
    health: 0.96,
    quorum: true,
    href: "https://szlholdings-immune.hf.space",
  },
  {
    id: "a11oy",
    name: "a11oy",
    role: "governed inference",
    domain: "command console",
    health: 0.91,
    quorum: true,
    href: "https://a-11-oy.com",
  },
  {
    id: "killinchu",
    name: "killinchu",
    role: "counter-UAS mesh",
    domain: "physical effectors",
    health: 0.88,
    quorum: true,
    href: "https://huggingface.co/spaces/SZLHOLDINGS/killinchu",
  },
  {
    id: "khipu",
    name: "Khipu-1.5B",
    role: "sovereign agent",
    domain: "proposes, never executes",
    health: 0.84,
    quorum: true,
    href: "https://huggingface.co/SZLHOLDINGS/SZL-Khipu-1.5B",
  },
];

export const GRAPH_EDGES: GraphEdge[] = [
  { from: "APT-GHOST", to: "IMMUNE", rel: "injects" },
  { from: "IMMUNE", to: "YAWAR", rel: "seals" },
  { from: "SENTRA", to: "IMMUNE", rel: "admits" },
  { from: "CISA KEV", to: "a11oy", rel: "watches" },
  { from: "killinchu", to: "IMMUNE", rel: "fuses" },
  { from: "Khipu-1.5B", to: "SENTRA", rel: "proposes" },
  { from: "APT-MIRROR", to: "Khipu-1.5B", rel: "exfils" },
  { from: "YAWAR", to: "Rekor", rel: "mirrors" },
  { from: "HUKLLA", to: "DEADMAN", rel: "trips" },
  { from: "CISA KEV", to: "IMMUNE", rel: "informs" },
];
